### ISSUE TITLE
Config files wont save

### ISSUE THREAD

**Issue by KanoBoii** [MichaelJW/DorsalVR#11]
Hey,

I seem to be coming across a quite an annoying issue, I've tried following the tutorial steps and going over them several times to see if I was doing something wrong, even tried making new folders and changed the parameters as needed but still no luck

If I change anything in the examples folder and save the changes, as soon as I start DorsalVR in Steam my changes are ignored and the YAML's are reverted back to their original state. (Non HMD mode being taken off) for example my ValveIndex grip changes get changed back. If I try to make it into a whole separate folder then everything works but my controller isn't being picked up

**Comment by MichaelJW** [comment]
Hey! Yeah I need to document this better: the /examples/ folder is effectively read-only in that it'll always get overwritten whenever DorsalVR is loaded.

Not sure why the controller wouldn't be picked up, though. Can you say more about that please? Any errors?

**Comment by KanoBoii** [comment]
Thank you for getting back to me, so with the controller issue none of the buttons work and I don't get a cursor on the screen (The Hand) so for example if I try playing Red Steel 2 I can't get onto the next screen, but this is with me creating my own configs. (i'll paste what it looks like down below) If I use the examples configs it all works perfect, all buttons work etc.

This is the main folder
![image](https://user-images.githubusercontent.com/91238298/134778540-bc8365ef-699a-428b-b489-368a88c3b15e.png)

The config folder
![image](https://user-images.githubusercontent.com/91238298/134778554-3a39b0a5-0399-40a1-8630-af823a787512.png)

The notepad config
![image](https://user-images.githubusercontent.com/91238298/134778575-1adf5fc1-d59f-47ed-889d-e2304d4d7772.png)

**Comment by KanoBoii** [comment]
The problem managed to rectify its self, sorry for causing any concern

**Comment by MichaelJW** [comment]
@KanoBoii Ah, that's great to hear! Sorry I missed your messages till now
