### ISSUE TITLE
TV not showing up in DorsalVR

### ISSUE THREAD

**Issue by JackTheRedCreeper** [MichaelJW/DorsalVR#19]
I can't seem to find the screen no matter how much I tweak WidescreenTV.yaml. For what it's worth, Dolphin picks my controllers' point by aiming downwards.
I've managed to get DorsalVR to work flawlessly (I'd dare say, even better than my actual wiimotes lol) while playing MadWorld - that game doesn't require pointing, so it's fine. I'm using a Valve Index setup

So far I've narrowed it down to assigning controls to Dolphin VR causing this problem. If I don't have any of those (example/wiimote.yaml for example) the screen appears, but it's all white. Changing position and/or scale doesn't do anything.

I'll be editing this as I keep trying further.

Edit: Apparently the screen appears even if my config file is empty... lolwut. DeviceIMUs doesn't work at all.

**Comment by JackTheRedCreeper** [comment]
Oh, huh, seems to be the same case as #17. Well, that's something for us non-english peeps: Get rid of decimals haha

**Comment by MichaelJW** [comment]
Hey, thanks for the update on this; I'll definitely look at that decimals issue!
